### ISSUE TITLE
Package version derived from GitHub not CRAN

### ISSUE THREAD

**Issue by hadley** [ourresearch/citeas-api#11]
e.g. http://citeas.org/cite/https://cran.r-project.org/web/packages/tidyr - citation should refer to the released version (0.7.2) not the development version.

**Comment by hpiwowar** [comment]
good point!  for now have removed the version from the citation until we can figure out a better way to fix this.

**Comment by bastistician** [comment]
This seems to be broken again. If the user requests a citation for https://cran.r-project.org/web/packages/tidyr, citeas should never parse the in-development DESCRIPTION file from GitHub but eventually fall back on the [DESCRIPTION from CRAN](https://cran.r-project.org/web/packages/tidyr/DESCRIPTION), which always exists.

**Comment by caseydm** [comment]
This should be fixed now, as the package version is pulled from the DESCRIPTION file on CRAN. Please take a look.

**Comment by caseydm** [comment]
This is an old issue, but I just double checked and everything is working correctly.
