### ISSUE TITLE
Does not identify DOIs from Zenodo badges

### ISSUE THREAD

**Issue by cboettig** [ourresearch/citeas-api#39]
E.g. https://github.com/cboettig/noise-phenomena has a zenodo DOI badge.

**Comment by caseydm** [comment]
I know this is an old issue, but want to update that this is working better now. CiteAs recognizes DOIs on the initial Github page. It detects the zenodo badge but there are some extra steps involved in resolving that to a full DOI. Should have it resolved shortly.

**Comment by caseydm** [comment]
Hello this is working now. I still need to refactor a bit, but the right citation is shown: https://github.com/cboettig/noise-phenomena
