### ISSUE TITLE
http://citeas.org/cite/NESOSIM only picks up first name

### ISSUE THREAD

**Issue by jameshowison** [ourresearch/citeas-api#54]
Using http://citeas.org/cite/NESOSIM the formed citation uses Alek which is just the first name.  With the "all routes" on it's hard to see where this is coming from and how we might improve it.  Can we show more clearly which information source is actually being used?  e.g., I went to the bottom one (API) but "Alek" doesn't appear there so it must be coming from elsewhere?

I think it would be useful to have a link that would show the citation that would be generated from each source.

**Comment by caseydm** [comment]
Hi James. The citation should be built entirely from the last source shown in the provenance. 

Technically, it was built off the API response at https://api.github.com/repos/akpetty/NESOSIM, as within that response is a link to author data at owner > url: https://api.github.com/users/akpetty. The author name comes from the 'name' field of that API response. That is the only data in the citation that is pulled from that link. 

So I suppose we could change the section under 'GitHub repository API response' to show:
`https://api.github.com/repos/akpetty/NESOSIM (software data), https://api.github.com/users/akpetty (author data)`

Do you think that would be clearer? Overall I think it's still accurate when it says at the bottom: `Parsing the GitHub repository API response, we found The citation metadata` so we could also leave it as is.

**Comment by jameshowison** [comment]
Thanks. Problem is that even looking closely the interface didn’t let me
figure that out. With multiple options bolded I wasn’t sure which had been
used. Then it wasn’t clear that we followed the user APO link.

This is during an interview so I have a user there who also couldn’t
follow. Thing is that we want to teach them to improve things. In this case
they should fix up the Name field, but how can we guide them to see that
clearly in the CiteAs interface?

**Comment by jameshowison** [comment]
Sounds good.  So the last step would highlight what was actually found and
used to make the citation?

**Comment by jameshowison** [comment]
Sounds like a plan.  We can see if it improves things in our interviews.
Anything else you wonder about that we should be asking about?

**Comment by caseydm** [comment]
Ok great! I can't think of anything right now. But I will contact you separately to learn more about the intent of the interview and what gets asked now. Think I need to understand that better, then I might have some ideas.

**Comment by caseydm** [comment]
Hello. As an update, the first three fixes have been implemented. Working on the fourth one. Let me know if you have feedback.

**Comment by caseydm** [comment]
The last step is complete for CRAN packages. Some examples:
http://citeas.org/cite/https://cran.r-project.org/web/packages/apsrtable/index.html
http://citeas.org/cite/https://cran.r-project.org/web/packages/stringr

You probably need to view in 'incognito' mode initially to get the updated stylesheets and scripts.

Please take a look and provide any feedback you may have. Once you are happy with this format I will implement it for other types of software (DOI, web page, etc). One issue I am working is to improve how the popups look on mobile.

**Comment by jameshowison** [comment]
Awesome! I think that will really help people understand.

**Comment by caifand** [comment]
This looks amazing. A tiny bit of parsing imperfection here:
![image](https://user-images.githubusercontent.com/35734860/65789657-74ba9280-e123-11e9-869e-c9c144b93294.png)

Chiming in as I also got some feedbacks, especially about the interface, during the interviews. Haven't got them all organized yet. Will get back to you @caseydm in days.

Thanks!

**Comment by caseydm** [comment]
Sounds great @caifand! As for the parsing issue, that is actually the source text being cut off at a certain number of characters, as it's not always feasible to show the entire document. If you can think of a better way to make that clear, let me know. Maybe add a '...' before?
