### ISSUE TITLE
Cannot pick the requested citation via project page

### ISSUE THREAD

**Issue by caifand** [ourresearch/citeas-api#56]
For example, Matplotlib has put its citation request on its website: [https://matplotlib.org/citing.html](https://matplotlib.org/citing.html) but neither its landing page [https://matplotlib.org](https://matplotlib.org) or the citing page itself can lead to this citing info. The Github repo is traced prior to that.

This one cannot be found, either: [http://marsbar.sourceforge.net/about.html#citing-marsbar](http://marsbar.sourceforge.net/about.html#citing-marsbar). It's a project hosted on sourceforge while its citation info is embedded in its documentation.

Thanks!

**Comment by caseydm** [comment]
Hello. When on a web page, CiteAs looks for GitHub repositories first, then DOIs, then bibtex. Your example demonstrates that it is likely better to look for a DOI or bibtex first. @jameshowison do you think we should change the order?

As for your second example, the software currently does not find plain-text citations through 'cite this project as' or other hints. But this is a feature that would be good to implement down the road.
