### ISSUE TITLE
CITATION.rst files are not being found neither the citation page from the docs

### ISSUE THREAD

**Issue by bsipocz** [ourresearch/citeas-api#57]
This experiment was running on the web form rather than directly using the API.

E.g. neither `ccdproc` or `photutils`. Both have zenodo DOIs.

(astroquery and astropy works as expected, and indeed the prefered way, the journal papers are being picked up)

**Comment by bsipocz** [comment]
OK, so the problem is probably with the fact that the files have the `rst` extension rather than lacking the extension. It might be a feasible feature request to extend the search for the CITATION file to find text files with extensions.

**Comment by caseydm** [comment]
Hello. Were you entering ccdproc and photoutils in as keyword terms? I found that CITATION files with an rst extension work just fine: http://citeas.org/cite/https://github.com/astropy/ccdproc

However, if you enter ccdproc or photoutils, the software returns the first search result for 'ccdproc software citation' which is this: https://ccdproc.readthedocs.io/en/latest/. Both of those terms leads to documentation at readthedocs, which are web pages that reference a citation.html file. But the software was not finding that citation.html file.

I fixed that so the citation.html files are found, which greatly improves the citation that is returned. You can take a look by trying these:

http://citeas.org/cite/https://photutils.readthedocs.io/
http://citeas.org/cite/ccdproc

Does that help with the issue?

**Comment by bsipocz** [comment]
> Were you entering ccdproc and photoutils in as keyword terms? 

yes, I tried these four as a search term, one-by-one

> I fixed that so the citation.html files are found

thank you, the result now looks much better. I'll add a link to the github page to the front `index.html`, or from the `citation.html` pages, maybe then also the github repo is being picked up.

**Comment by caseydm** [comment]
Sounds great!
