### ISSUE TITLE
Make CiteAs citable :)

### ISSUE THREAD

**Issue by caifand** [ourresearch/citeas-api#59]
See -> http://citeas.org/cite/citeas

When we were doing user interviews they especially like to experiment CiteAs with CiteAs so this was not the first time we saw this feedback ...

To make it more "parsable" seems we either have a citation metadata file for CiteAs or modify the {About} page a bit?

**Comment by caseydm** [comment]
This is fixed: http://citeas.org/cite/http://citeas.org/about. CiteAs now detects the web page title just like it does with other web pages. 

It would be nice if the github repositories that are mentioned on the page were detected, but when you view source for the About page the content on the page is displayed with scripts and not available to be parsed.
