### ISSUE TITLE
Error parsing dib-lab/sourmash

### ISSUE THREAD

**Issue by luizirber** [ourresearch/citeas-api#60]
Hi!

citeas is super cool! I saw an example with [bokeh] and tried it out with my project, [sourmash]... and it didn't work. From the bokeh output it seems we have even more sources (codemeta, citation.cff), but none is picked up?

[bokeh]: https://citeas.org/cite/https://github.com/bokeh/bokeh
[sourmash]: https://citeas.org/cite/https://github.com/dib-lab/sourmash

While checking the API: http://api.citeas.org/product/https://github.com/dib-lab/sourmash
I noticed there is an error 500, so are we doing something too weird in the repo?

**Comment by caseydm** [comment]
Hi! Glad you are enjoying citeas. This is fixed now. The error was on our end, in that we were not handing this portion of your codemeta file properly:

`identifier: "",`

We weren't treating that value as None, and were trying to parse a DOI that is sometimes there. But the script now sees that as an empty value and moves on. Take a look and let me know if you see any other issues.

**Comment by luizirber** [comment]
Thanks for the quick reply, @caseydm!

And... That's an error on our side, that identifier should be a DOI, and we should have authors listed too :rofl:. I'll fix it and try again, but already glad to see it is showing up on citeas!
