### ISSUE TITLE
wrong citation count?

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/citeas-api#61]
From twitter:  https://twitter.com/hauschke/status/1217469849322033153

"A work is cited 6759 times according to #PaperBuzz (is-referenced-by-count in https://api.paperbuzz.org/v0/doi/10.1175/bams-d-11-00094.1). Where does this information come from? I couldn't find public info about this. Cited-by from Crossref?"

**Comment by hauschke** [comment]
Thanks a lot for creating this issue, @hpiwowar. I do not doubt the citation count, I just miss provenance information. Could provenance information for this (and other data in Paperbuzz and elsewhere) be added. This would allow for using Paperbuzz according to DORA and Leiden Manifesto.

**Comment by caseydm** [comment]
Hello! I updated the Paperbuzz [about page](http://paperbuzz.org/about) to show where the data comes from. Bottom line is that the primary source of data is the Crossref [Event Data API](https://www.crossref.org/services/event-data/).

By provenance do you mean a link in the API response showing where we retrieved the data from? So maybe include the crossref API link such as this?

https://api.eventdata.crossref.org/v1/events?rows=10000&filter=from-collected-date:1990-01-01,until-collected-date:2099-01-01,obj-id:10.1371/journal.pone.0177707

**Comment by hauschke** [comment]
Yes, in the API there should be visible where the data came from.

**Comment by caseydm** [comment]
Ok, the provenance link is there in the API response under `crossref_event_data_url` and is covered in the [API documentation](http://paperbuzz.org/api).
