### ISSUE TITLE
Lookup fails when DESCRIPTION is missing Author field

### ISSUE THREAD

**Issue by mwoodbri** [ourresearch/citeas-api#62]
Steps to reproduce:
* Visit http://api.citeas.org/product/https://github.com/mrc-ide/PlasmoMAPI

**Comment by mwoodbri** [comment]
This is already fixed by f472475 but I just wanted to say thank you pre-empting my bug report and for all your work on CiteAs!

**Comment by caseydm** [comment]
You're welcome!
