### ISSUE TITLE
Can we follow pinned repos from github organizations?

### ISSUE THREAD

**Issue by jameshowison** [ourresearch/citeas-api#63]
starting at http://dbdp.org we get linked to a github organization, which has a pinned repo.  https://github.com/DigitalBiomarkerDiscoveryPipeline --> https://github.com/DigitalBiomarkerDiscoveryPipeline/DBDP

**Comment by caseydm** [comment]
Hi James. CiteAs now follows pinned repositories, somewhat of a last resort when a DOI or other source is not found. 

We will probably need watch for effects on other citations, as any time the software runs into a github URL from a web page that is an organization page, it will return the first pinned URL if there is one. If you have a better idea on how to filter this please let me know. But the example you posted works better now.
