### ISSUE TITLE
identify text citation given on the project landing page

### ISSUE THREAD

**Issue by caifand** [ourresearch/citeas-api#64]
Hi we are doing a demo presentation here :)

We have found that CWL (Common Workflow Language) has their citation claimed on the project landing page:
[https://www.commonwl.org/](https://www.commonwl.org/)

However we do not get the citation results as the homepage intends:
[http://citeas.org/cite/CWL](http://citeas.org/cite/CWL)

Thanks for looking into it!

**Comment by caseydm** [comment]
Hello! As of right now CiteAs is not set up to follow language such as 'use this citation' or detect a citation format on a web page and parse it. So with CWL CiteAs worked as intended and found the DOI that was referenced in the citation, and used that to build a new citation which is similar to what the authors intended.

Finding author-intended citations is something we will continue to look into.
