### ISSUE TITLE
Run CiteAs in docker for bulk requests?

### ISSUE THREAD

**Issue by jameshowison** [ourresearch/citeas-api#65]
We have some extractions from publications, numbering in the nearly 10,000 range.  We'd like to run those through CiteAs to see what the rate/style of requesting citations is.  This seems like something maybe better done via Docker rather through the webapp.  I'm not sure where things are hosted and whether that might blow some budget?

Might you be able to document running this via Docker? (Apologies if already done!)

**Comment by jameshowison** [comment]
@jasonpriem @caseydm Any ideas here?

**Comment by caseydm** [comment]
Hi James. Sorry for the delay. Are you talking about a docker version of the API only? I could set that up fairly easily. 

As for running against the web site, we could increase the capacity for a little while and it would not cost very much. I would imagine you could run those 10,000 requests in a couple days without many issues. But I'll get the docker version done so you can choose which to use.

**Comment by jameshowison** [comment]
Thanks Casey! Yeah, I think a docker version would be awesome, as we might
have reason to run this across mentions in the millions.  How much time do
you think that might take?

**Comment by caseydm** [comment]
Yes I can imagine the use in other areas would be nice. I should be able to get it uploaded with instructions by end of the day today.

**Comment by caseydm** [comment]
Ok you can go ahead and try it out. Instructions are in the readme: https://github.com/ourresearch/citeas-api

**Comment by jameshowison** [comment]
Awesome, worked perfectly for me.  Thanks!

**Comment by caseydm** [comment]
Great!
