### ISSUE TITLE
Follow links like "publications" to find citations from webpages?

### ISSUE THREAD

**Issue by jameshowison** [ourresearch/citeas-api#7]
e.g.,

http://agaveapi.co/ has its request for citation on the  https://agaveapi.co/publications/ page. It is under the About tab.

Perhaps scan the page for links associated with "Publication" or "Cite"?  I'm thinking only follow one link deep?

--J

**Comment by danielskatz** [comment]
It seems like this is going to be relatively hard to do automatically, though it makes sense to try
